In [58]:
import pickle
import pandas as pd
import joblib

In [59]:
new_data = pd.read_excel('new_data.xlsx')
new_data.head()

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,66,28,120000,MORTGAGE,13,VENTURE,C,7200,14.72,0.06,Y,6
1,67,26,30000,RENT,2,MEDICAL,A,12000,7.51,0.40,N,4
2,68,31,62900,MORTGAGE,2,MEDICAL,D,18000,14.09,0.24,N,5
3,69,24,40000,RENT,3,MEDICAL,C,3000,13.22,0.07,N,4
4,70,43,68000,MORTGAGE,0,MEDICAL,A,5000,8.90,0.07,N,17

In [60]:


# Load it using joblib instead of pickle
trained_model = joblib.load('random_forest_model.pkl')

print(type(trained_model))
with open('model_columns.pkl', 'rb') as f:
    model_columns = pickle.load(f)

<class 'sklearn.ensemble._forest.RandomForestClassifier'>

In [61]:
# 2. Get dummies on your new data
new_df_encoded = pd.get_dummies(new_data , drop_first = True)

# 3. ALIGNMENT STEP: 
# Add any missing columns that were in training but are missing now (fill with 0)
for col in model_columns:
    if col not in new_df_encoded.columns:
        new_df_encoded[col] = 0

# 4. Ensure the exact same column order as training
# (This also drops any brand new columns the model hasn't seen before)
new_df_encoded = new_df_encoded[model_columns]
new_df_encoded.head()

,id,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,person_home_ownership_OTHER,person_home_ownership_OWN,...,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE,loan_grade_B,loan_grade_C,loan_grade_D,loan_grade_E,loan_grade_F,loan_grade_G,cb_person_default_on_file_Y
0,66,28,120000,13,7200,14.72,0.06,6,0,False,...,False,False,True,False,True,False,0,0,0,True
1,67,26,30000,2,12000,7.51,0.40,4,0,False,...,True,False,False,False,False,False,0,0,0,False
2,68,31,62900,2,18000,14.09,0.24,5,0,False,...,True,False,False,False,False,True,0,0,0,False
3,69,24,40000,3,3000,13.22,0.07,4,0,False,...,True,False,False,False,True,False,0,0,0,False
4,70,43,68000,0,5000,8.90,0.07,17,0,False,...,True,False,False,False,False,False,0,0,0,False

In [62]:
predictions = trained_model.predict(new_df_encoded)

print(predictions)

[0 1 1 0 0 0 0 0 0 0]